# .github/workflows/build-and-deploy.yml

name: Build & Deploy Jekyll Site with Vanilla Setup

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:  # ← permite ejecución manual desde la interfaz

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # O ajusta según tu entorno local

      - name: Install Jekyll and Bundler
        run: |
          gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build --source ./ --destination ./_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          force_orphan: true